apiVersion: v1
kind: Service
metadata:
  name: dice-signalr-service
spec:
  selector:
    app: dice-service
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-deployment
spec:
  selector:
    matchLabels:
      app: dice-service
  template:
    metadata:
      labels:
        app: dice-service
    spec:
      containers:
      - name: dice-service
        image: bdbishopdev/signalr-dice-server:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

