apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: my-nginx
  template:
    metadata:
      labels:
        tier: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
         
